---
  name: docker-builder-edge
  on:
    push:
      branches:
        - 'multi-arch-image-builds'
    repository_dispatch:
      types:
        - refresh

  jobs:
    docker:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: true
        matrix:
          python_version:
            - 3.8
            # - 3.6
            # - 3.9
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Inspect builder
          run: |
            echo "Name:      ${{ steps.buildx.outputs.name }}"
            echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
            echo "Status:    ${{ steps.buildx.outputs.status }}"
            echo "Flags:     ${{ steps.buildx.outputs.flags }}"
            echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

        - name: Docker meta for EDGE
          id: meta
          uses: docker/metadata-action@v3
          if: startsWith(github.ref, 'refs/heads/multi-arch-image-builds')
          with:
            images: ${{ secrets.DOCKER_IMAGE }}
            tags: |
              type=edge,prefix=${{matrix.python_version}}-

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ${{ matrix.python_version }}/Dockerfile
            platforms: linux/amd64, linux/arm64/v8, linux/arm/v7
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
